version: '3.7'

services:
  hanabilive:
    image: tkw01536/hanabi_live
    ports:
      - 8080:8080
    environment:
      - HANABI_DOMAIN=${DOMAIN}
      - HANABI_SESSION_SECRET=${SECRET}
      - HANABI_DB_HOST=mariadb
      - HANABI_DB_PORT=3306
      - HANABI_DB_NAME=${DB_NAME}
      - HANABI_DB_USER=${DB_USER}
      - HANABI_DB_PASS=${DB_PASS}
    depends_on:
      - mariadb
    restart: always
  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: always

volumes:
    mariadb:
